server:
  port: 9301

spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.193.30:8848
    sentinel:
      transport:
        dashboard: 192.168.193.30:8081
        port: 8719
        client-ip: 192.168.193.31

feign:
  sentinel:
    enabled: true